[package]
name = "tw-macro"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
daisyui = []

# workspace = "."

[dependencies]
syn = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
nom = { workspace = true }
static_assertions = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
regex = { workspace = true }
# tailwindcss-core = { workspace = true }


[lib]
proc-macro = true
